---
- name: Install selinux lib
  yum: pkg={{item}} state=present
  with_items:
      - libselinux-python
  register: result
  notify:
      - Gather facts

- name: Gather facts if changed
  setup:
  when: result|changed

